import { AnalysisResult } from './emailAnalyzer';
import { HeaderAnalysisResult } from './headerAnalyzer';
import { VTUrlResult } from './virusTotalApi';

export interface ReportOptions {
  /** Mask email addresses and strip URL paths/queries (client reports). */
  anonymize?: boolean;
}

/** "paul.levy@client.co.il" -> "p***@client.co.il" */
export function maskEmail(email: string): string {
  return email.replace(/([A-Za-z0-9._%+-])[A-Za-z0-9._%+-]*@([A-Za-z0-9.-]+\.[A-Za-z]{2,})/g, '$1***@$2');
}

/** Keeps scheme + host only: "https://evil.example/login?u=paul" -> "https://evil.example/…" */
export function maskUrl(url: string): string {
  const m = /^([a-z][a-z0-9+.-]*:\/\/[^/?#\s]+)(.*)$/i.exec(url.trim());
  if (!m) return maskEmail(url);
  return m[2] && m[2] !== '/' ? `${m[1]}/…` : m[1];
}

/** Masks emails, then URLs, inside free text. */
export function anonymizeText(text: string): string {
  return maskEmail(text).replace(/https?:\/\/[^\s"'<>)]+/gi, (u) => maskUrl(u));
}

export function generateTextReport(
  senderEmail: string,
  result: AnalysisResult,
  headerResult: HeaderAnalysisResult | null,
  vtResults: VTUrlResult[] | null,
  options: ReportOptions = {}
): string {
  const text = buildReport(senderEmail, result, headerResult, vtResults);
  return options.anonymize ? anonymizeText(text) : text;
}

function buildReport(
  senderEmail: string,
  result: AnalysisResult,
  headerResult: HeaderAnalysisResult | null,
  vtResults: VTUrlResult[] | null
): string {
  const lines: string[] = [];
  const divider = '─'.repeat(50);
  const date = new Date().toLocaleString();

  lines.push('IT SECURITY ASSISTANT — ANALYSIS REPORT');
  lines.push(divider);
  lines.push(`Date        : ${date}`);
  lines.push(`Sender      : ${senderEmail || '(not provided)'}`);
  lines.push(`Risk Level  : ${result.level.toUpperCase()}`);
  lines.push(`Risk Score  : ${result.score}/100`);
  lines.push(divider);

  lines.push('\nDETECTED ISSUES');
  result.issues.forEach((issue) => lines.push(`  • ${issue}`));

  if (result.suspiciousUrls.length > 0) {
    lines.push('\nSUSPICIOUS URLs');
    result.suspiciousUrls.forEach((u) => {
      lines.push(`  • ${u.url}`);
      lines.push(`    → ${u.reason}`);
    });
  }

  if (result.suspiciousAttachments.length > 0) {
    lines.push('\nSUSPICIOUS ATTACHMENTS');
    result.suspiciousAttachments.forEach((a) => {
      lines.push(`  • ${a.name}`);
      lines.push(`    → ${a.reason}`);
    });
  }

  if (vtResults && vtResults.length > 0) {
    lines.push('\nVIRUSTOTAL SCAN');
    vtResults.forEach((vt) => {
      const verdict =
        vt.status === 'malicious'
          ? `MALICIOUS (${vt.malicious}/${vt.total} engines)`
          : vt.status === 'suspicious'
          ? `SUSPICIOUS (${vt.suspicious}/${vt.total} engines)`
          : vt.status === 'clean'
          ? `Clean (0/${vt.total} engines)`
          : vt.errorMessage ?? 'Unknown';
      lines.push(`  • ${vt.url}`);
      lines.push(`    → ${verdict}`);
    });
  }

  if (headerResult && headerResult.detections.length > 0) {
    lines.push('\nHEADER ANALYSIS');
    lines.push(`Header Risk Score: ${headerResult.score}/100`);
    headerResult.detections.forEach((d) => {
      lines.push(`  • [${d.header}] ${d.reason}`);
      lines.push(`    Value: ${d.value.slice(0, 100)}${d.value.length > 100 ? '...' : ''}`);
    });
  }

  lines.push('\nEXPLANATION');
  lines.push(`  ${result.explanation}`);

  lines.push('\nRECOMMENDATIONS');
  result.recommendations.forEach((r, i) => lines.push(`  ${i + 1}. ${r}`));

  lines.push('\n' + divider);
  lines.push('Generated by IT Security Assistant — For internal security awareness use only');

  return lines.join('\n');
}

export async function copyReportToClipboard(
  senderEmail: string,
  result: AnalysisResult,
  headerResult: HeaderAnalysisResult | null,
  vtResults: VTUrlResult[] | null,
  options: ReportOptions = {}
): Promise<void> {
  const text = generateTextReport(senderEmail, result, headerResult, vtResults, options);
  await navigator.clipboard.writeText(text);
}
